version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-regulaflow
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: regulaflow_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: